### ISSUE TITLE
Избавиться от этого костыля

### ISSUE THREAD

**Issue by Kuprov-dev** [beyang-crypto/CCXT_beYANG#2]
```
	defer func() {
		cerr := res.Body.Close()
		// Only overwrite the retured error if the original error was nil and an
		// error occurred while closing the body.
		if err == nil && cerr != nil {
			err = cerr
		}
	}()
```
обработать ошибку правильно

**Comment by MarloGrayhat** [comment]
defer res.Body.Close()

Ошибка не возникает ни при каких обстоятельствах (Если читать документацию).
Даже в официальной документации ошибка не обрабатывается https://pkg.go.dev/net/http
